POST http://localhost:8080/create-developer
Content-Type: application/json

{
  "developerLevel" : "JUNIOR",
  "developerSkillType": "FRONT_END",
  "experienceYears": 2,
  "memberId": "yurrrrr_i",
  "name": "Yuri",
  "age": 30
}